// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV8NvNPWhnlSWbROXf2iLgOV_mDothCNA',
    appId: '1:1033080986632:web:f42a4aa69460d67a87c5bd',
    messagingSenderId: '1033080986632',
    projectId: 'mapmemory-87',
    authDomain: 'mapmemory-87.firebaseapp.com',
    databaseURL: 'https://mapmemory-87-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mapmemory-87.appspot.com',
    measurementId: 'G-VDK96VVC4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeX810m5p3XuyrF1Ok5f2QHR401wuj8GI',
    appId: '1:1033080986632:android:6326cf61d4fbfc7787c5bd',
    messagingSenderId: '1033080986632',
    projectId: 'mapmemory-87',
    databaseURL: 'https://mapmemory-87-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mapmemory-87.appspot.com',
  );
}
